// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package connectivity

import (
	"github.com/Web-tree/d-compute/network/connectivity/invitation"
	"github.com/Web-tree/d-compute/network/connectivity/pool"
	"github.com/Web-tree/d-compute/network/connectivity/topology"
	"github.com/Web-tree/d-compute/network/keys"
	"github.com/Web-tree/d-compute/network/local"
)

// Injectors from wire.go:

func Initialize() ConnectionService {
	minConnectedNodes := defaultMinConnectedNodes()
	maxConnectedNodes := defaultMaxConnectedNodes()
	db := local.GetInstance()
	connectionPool := pool.GetInstance()
	config := keys.Conf()
	keysService := keys.NewKeysService(config)
	invitationConfig := invitation.Conf()
	invitationService := invitation.NewService(invitationConfig)
	topologyConfig := topology.Conf()
	topologyService := topology.NewService(topologyConfig)
	connectivityConnectionService := newConnectionService(minConnectedNodes, maxConnectedNodes, db, connectionPool, keysService, invitationService, topologyService)
	return connectivityConnectionService
}

// wire.go:

func defaultMaxConnectedNodes() topology.MaxConnectedNodes {
	return 1000
}

func defaultMinConnectedNodes() topology.MinConnectedNodes {
	return 50
}
