// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package pool

// Injectors from wire.go:

func GetInstance() ConnectionPool {
	poolConnectionPool := newConnectionPool()
	return poolConnectionPool
}
