// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: proto/invitation.proto

package invitation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AcceptInvitation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InvitationId string `protobuf:"bytes,1,opt,name=InvitationId,proto3" json:"InvitationId,omitempty"`
	HostId       string `protobuf:"bytes,2,opt,name=HostId,proto3" json:"HostId,omitempty"`
	PublicKey    []byte `protobuf:"bytes,3,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
}

func (x *AcceptInvitation) Reset() {
	*x = AcceptInvitation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_invitation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptInvitation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptInvitation) ProtoMessage() {}

func (x *AcceptInvitation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_invitation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptInvitation.ProtoReflect.Descriptor instead.
func (*AcceptInvitation) Descriptor() ([]byte, []int) {
	return file_proto_invitation_proto_rawDescGZIP(), []int{0}
}

func (x *AcceptInvitation) GetInvitationId() string {
	if x != nil {
		return x.InvitationId
	}
	return ""
}

func (x *AcceptInvitation) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *AcceptInvitation) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

var File_proto_invitation_proto protoreflect.FileDescriptor

var file_proto_invitation_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x6c, 0x0a, 0x10, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x49, 0x6e,
	0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x49, 0x6e, 0x76, 0x69,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x49, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x48, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x48, 0x6f,
	0x73, 0x74, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b,
	0x65, 0x79, 0x42, 0x19, 0x5a, 0x17, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x2f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_invitation_proto_rawDescOnce sync.Once
	file_proto_invitation_proto_rawDescData = file_proto_invitation_proto_rawDesc
)

func file_proto_invitation_proto_rawDescGZIP() []byte {
	file_proto_invitation_proto_rawDescOnce.Do(func() {
		file_proto_invitation_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_invitation_proto_rawDescData)
	})
	return file_proto_invitation_proto_rawDescData
}

var file_proto_invitation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_invitation_proto_goTypes = []interface{}{
	(*AcceptInvitation)(nil), // 0: invitation.AcceptInvitation
}
var file_proto_invitation_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_invitation_proto_init() }
func file_proto_invitation_proto_init() {
	if File_proto_invitation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_invitation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcceptInvitation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_invitation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_invitation_proto_goTypes,
		DependencyIndexes: file_proto_invitation_proto_depIdxs,
		MessageInfos:      file_proto_invitation_proto_msgTypes,
	}.Build()
	File_proto_invitation_proto = out.File
	file_proto_invitation_proto_rawDesc = nil
	file_proto_invitation_proto_goTypes = nil
	file_proto_invitation_proto_depIdxs = nil
}
