// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package local

// Injectors from wire.go:

func GetInstance() Db {
	string2 := DbPath()
	db := newDb(string2)
	return db
}
