// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package runner

import (
	"github.com/Web-tree/d-compute/network/connectivity"
)

// Injectors from wire.go:

func InitializeRunner() Runner {
	connectionService := connectivity.Initialize()
	runnerRunner := newRunner(connectionService)
	return runnerRunner
}
